### ISSUE TITLE
[Errno 2] No such file or directory: '../data/voc2012/VOCdevkit/VOC2012/train.txt'

### ISSUE THREAD

**Issue by thanujTa** [LongxingTan/Yolov5#25]
when executing -   ! python train.py, there's an error showing up  - [Errno 2] No such file or directory: '../data/voc2012/VOCdevkit/VOC2012/train.txt' 

I tried to look for the .txt file in the given directory, but I couldn't find it. Did anyone else have this same issue?

I also checked the read_data.py script, but I cant seem to find the directory linked to it. How to resolve this issue.

To be clear here's the entire error:

Traceback (most recent call last):
  File "/home/jovyan/Yolov5/yolo/train.py", line 153, in <module>
    DataReader = DataReader(params['train_annotations_dir'], img_size=params['img_size'], transforms=transforms,
  File "/home/jovyan/Yolov5/yolo/dataset/read_data.py", line 21, in __init__
    self.annotations = self.load_annotations(annotations_dir)
  File "/home/jovyan/Yolov5/yolo/dataset/read_data.py", line 65, in load_annotations
    with open(annotations_dir, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../data/voc2012/VOCdevkit/VOC2012/train.txt'

**Comment by LongxingTan** [comment]
@thanujTa 

You could download the data first, like the script 
[https://github.com/LongxingTan/tfyolo/blob/main/data/scripts/get_voc.sh](https://github.com/LongxingTan/tfyolo/blob/main/data/scripts/get_voc.sh)

**Comment by ds-seungwan** [comment]
FileNotFoundError: [Errno 2] No such file or directory: '../tfyolo/data/voc/voc.names'
 -> i tried bash data/scripts/get_voc.sh
